<?php

const SL3W_WATERMARK_SESSION_DATA_CONTAINER = 'sl3w_data';
const SL3W_WATERMARK_DONT_ADD_PROP_NAME = 'DONT_ADD_WATERMARK_ON_SAVE';
const SL3W_WATERMARK_PENDING_1C_PROCESS_START_AFTER_SECONDS = 300; //5 minutes